services:
  ficheeuro:
    build: .
    container_name: ficheeuro
    restart: unless-stopped
    network_mode: host
    environment:
      - PORT=10100
      - SITE_BRAND=eu
      - VAR_DIR=/app/var
    volumes:
      - ./var:/app/var
