// EU member-state names per UI locale, keyed by the ISO code used in the data
// (note: Greece is "GR" here, not "EL"). Localized names matter for EU SEO — a
// German voter searches "Abgeordnete Finnland", not "Finland".
const NAMES = {
  AT: { bg: "Австрия", cs: "Rakousko", da: "Østrig", de: "Österreich", el: "Αυστρία", en: "Austria", es: "Austria", et: "Austria", fi: "Itävalta", fr: "Autriche", ga: "An Ostair", hr: "Austrija", hu: "Ausztria", it: "Austria", lt: "Austrija", lv: "Austrija", mt: "Awstrija", nl: "Oostenrijk", pl: "Austria", pt: "Áustria", ro: "Austria", sk: "Rakúsko", sl: "Avstrija", sv: "Österrike" },
  BE: { bg: "Белгия", cs: "Belgie", da: "Belgien", de: "Belgien", el: "Βέλγιο", en: "Belgium", es: "Bélgica", et: "Belgia", fi: "Belgia", fr: "Belgique", ga: "An Bheilg", hr: "Belgija", hu: "Belgium", it: "Belgio", lt: "Belgija", lv: "Beļģija", mt: "Belġju", nl: "België", pl: "Belgia", pt: "Bélgica", ro: "Belgia", sk: "Belgicko", sl: "Belgija", sv: "Belgien" },
  BG: { bg: "България", cs: "Bulharsko", da: "Bulgarien", de: "Bulgarien", el: "Βουλγαρία", en: "Bulgaria", es: "Bulgaria", et: "Bulgaaria", fi: "Bulgaria", fr: "Bulgarie", ga: "An Bhulgáir", hr: "Bugarska", hu: "Bulgária", it: "Bulgaria", lt: "Bulgarija", lv: "Bulgārija", mt: "Bulgarija", nl: "Bulgarije", pl: "Bułgaria", pt: "Bulgária", ro: "Bulgaria", sk: "Bulharsko", sl: "Bolgarija", sv: "Bulgarien" },
  HR: { bg: "Хърватия", cs: "Chorvatsko", da: "Kroatien", de: "Kroatien", el: "Κροατία", en: "Croatia", es: "Croacia", et: "Horvaatia", fi: "Kroatia", fr: "Croatie", ga: "An Chróit", hr: "Hrvatska", hu: "Horvátország", it: "Croazia", lt: "Kroatija", lv: "Horvātija", mt: "Kroazja", nl: "Kroatië", pl: "Chorwacja", pt: "Croácia", ro: "Croația", sk: "Chorvátsko", sl: "Hrvaška", sv: "Kroatien" },
  CY: { bg: "Кипър", cs: "Kypr", da: "Cypern", de: "Zypern", el: "Κύπρος", en: "Cyprus", es: "Chipre", et: "Küpros", fi: "Kypros", fr: "Chypre", ga: "An Chipir", hr: "Cipar", hu: "Ciprus", it: "Cipro", lt: "Kipras", lv: "Kipra", mt: "Ċipru", nl: "Cyprus", pl: "Cypr", pt: "Chipre", ro: "Cipru", sk: "Cyprus", sl: "Ciper", sv: "Cypern" },
  CZ: { bg: "Чехия", cs: "Česko", da: "Tjekkiet", de: "Tschechien", el: "Τσεχία", en: "Czechia", es: "Chequia", et: "Tšehhi", fi: "Tšekki", fr: "Tchéquie", ga: "An tSeicia", hr: "Češka", hu: "Csehország", it: "Cechia", lt: "Čekija", lv: "Čehija", mt: "Ċekja", nl: "Tsjechië", pl: "Czechy", pt: "Chéquia", ro: "Cehia", sk: "Česko", sl: "Češka", sv: "Tjeckien" },
  DK: { bg: "Дания", cs: "Dánsko", da: "Danmark", de: "Dänemark", el: "Δανία", en: "Denmark", es: "Dinamarca", et: "Taani", fi: "Tanska", fr: "Danemark", ga: "An Danmhairg", hr: "Danska", hu: "Dánia", it: "Danimarca", lt: "Danija", lv: "Dānija", mt: "Danimarka", nl: "Denemarken", pl: "Dania", pt: "Dinamarca", ro: "Danemarca", sk: "Dánsko", sl: "Danska", sv: "Danmark" },
  EE: { bg: "Естония", cs: "Estonsko", da: "Estland", de: "Estland", el: "Εσθονία", en: "Estonia", es: "Estonia", et: "Eesti", fi: "Viro", fr: "Estonie", ga: "An Eastóin", hr: "Estonija", hu: "Észtország", it: "Estonia", lt: "Estija", lv: "Igaunija", mt: "Estonja", nl: "Estland", pl: "Estonia", pt: "Estónia", ro: "Estonia", sk: "Estónsko", sl: "Estonija", sv: "Estland" },
  FI: { bg: "Финландия", cs: "Finsko", da: "Finland", de: "Finnland", el: "Φινλανδία", en: "Finland", es: "Finlandia", et: "Soome", fi: "Suomi", fr: "Finlande", ga: "An Fhionlainn", hr: "Finska", hu: "Finnország", it: "Finlandia", lt: "Suomija", lv: "Somija", mt: "Finlandja", nl: "Finland", pl: "Finlandia", pt: "Finlândia", ro: "Finlanda", sk: "Fínsko", sl: "Finska", sv: "Finland" },
  FR: { bg: "Франция", cs: "Francie", da: "Frankrig", de: "Frankreich", el: "Γαλλία", en: "France", es: "Francia", et: "Prantsusmaa", fi: "Ranska", fr: "France", ga: "An Fhrainc", hr: "Francuska", hu: "Franciaország", it: "Francia", lt: "Prancūzija", lv: "Francija", mt: "Franza", nl: "Frankrijk", pl: "Francja", pt: "França", ro: "Franța", sk: "Francúzsko", sl: "Francija", sv: "Frankrike" },
  DE: { bg: "Германия", cs: "Německo", da: "Tyskland", de: "Deutschland", el: "Γερμανία", en: "Germany", es: "Alemania", et: "Saksamaa", fi: "Saksa", fr: "Allemagne", ga: "An Ghearmáin", hr: "Njemačka", hu: "Németország", it: "Germania", lt: "Vokietija", lv: "Vācija", mt: "Ġermanja", nl: "Duitsland", pl: "Niemcy", pt: "Alemanha", ro: "Germania", sk: "Nemecko", sl: "Nemčija", sv: "Tyskland" },
  GR: { bg: "Гърция", cs: "Řecko", da: "Grækenland", de: "Griechenland", el: "Ελλάδα", en: "Greece", es: "Grecia", et: "Kreeka", fi: "Kreikka", fr: "Grèce", ga: "An Ghréig", hr: "Grčka", hu: "Görögország", it: "Grecia", lt: "Graikija", lv: "Grieķija", mt: "Greċja", nl: "Griekenland", pl: "Grecja", pt: "Grécia", ro: "Grecia", sk: "Grécko", sl: "Grčija", sv: "Grekland" },
  HU: { bg: "Унгария", cs: "Maďarsko", da: "Ungarn", de: "Ungarn", el: "Ουγγαρία", en: "Hungary", es: "Hungría", et: "Ungari", fi: "Unkari", fr: "Hongrie", ga: "An Ungáir", hr: "Mađarska", hu: "Magyarország", it: "Ungheria", lt: "Vengrija", lv: "Ungārija", mt: "Ungerija", nl: "Hongarije", pl: "Węgry", pt: "Hungria", ro: "Ungaria", sk: "Maďarsko", sl: "Madžarska", sv: "Ungern" },
  IE: { bg: "Ирландия", cs: "Irsko", da: "Irland", de: "Irland", el: "Ιρλανδία", en: "Ireland", es: "Irlanda", et: "Iirimaa", fi: "Irlanti", fr: "Irlande", ga: "Éire", hr: "Irska", hu: "Írország", it: "Irlanda", lt: "Airija", lv: "Īrija", mt: "Irlanda", nl: "Ierland", pl: "Irlandia", pt: "Irlanda", ro: "Irlanda", sk: "Írsko", sl: "Irska", sv: "Irland" },
  IT: { bg: "Италия", cs: "Itálie", da: "Italien", de: "Italien", el: "Ιταλία", en: "Italy", es: "Italia", et: "Itaalia", fi: "Italia", fr: "Italie", ga: "An Iodáil", hr: "Italija", hu: "Olaszország", it: "Italia", lt: "Italija", lv: "Itālija", mt: "Italja", nl: "Italië", pl: "Włochy", pt: "Itália", ro: "Italia", sk: "Taliansko", sl: "Italija", sv: "Italien" },
  LV: { bg: "Латвия", cs: "Lotyšsko", da: "Letland", de: "Lettland", el: "Λετονία", en: "Latvia", es: "Letonia", et: "Läti", fi: "Latvia", fr: "Lettonie", ga: "An Laitvia", hr: "Latvija", hu: "Lettország", it: "Lettonia", lt: "Latvija", lv: "Latvija", mt: "Latvja", nl: "Letland", pl: "Łotwa", pt: "Letónia", ro: "Letonia", sk: "Lotyšsko", sl: "Latvija", sv: "Lettland" },
  LT: { bg: "Литва", cs: "Litva", da: "Litauen", de: "Litauen", el: "Λιθουανία", en: "Lithuania", es: "Lituania", et: "Leedu", fi: "Liettua", fr: "Lituanie", ga: "An Liotuáin", hr: "Litva", hu: "Litvánia", it: "Lituania", lt: "Lietuva", lv: "Lietuva", mt: "Litwanja", nl: "Litouwen", pl: "Litwa", pt: "Lituânia", ro: "Lituania", sk: "Litva", sl: "Litva", sv: "Litauen" },
  LU: { bg: "Люксембург", cs: "Lucembursko", da: "Luxembourg", de: "Luxemburg", el: "Λουξεμβούργο", en: "Luxembourg", es: "Luxemburgo", et: "Luksemburg", fi: "Luxemburg", fr: "Luxembourg", ga: "Lucsamburg", hr: "Luksemburg", hu: "Luxemburg", it: "Lussemburgo", lt: "Liuksemburgas", lv: "Luksemburga", mt: "Lussemburgu", nl: "Luxemburg", pl: "Luksemburg", pt: "Luxemburgo", ro: "Luxemburg", sk: "Luxembursko", sl: "Luksemburg", sv: "Luxemburg" },
  MT: { bg: "Малта", cs: "Malta", da: "Malta", de: "Malta", el: "Μάλτα", en: "Malta", es: "Malta", et: "Malta", fi: "Malta", fr: "Malte", ga: "Málta", hr: "Malta", hu: "Málta", it: "Malta", lt: "Malta", lv: "Malta", mt: "Malta", nl: "Malta", pl: "Malta", pt: "Malta", ro: "Malta", sk: "Malta", sl: "Malta", sv: "Malta" },
  NL: { bg: "Нидерландия", cs: "Nizozemsko", da: "Nederlandene", de: "Niederlande", el: "Κάτω Χώρες", en: "Netherlands", es: "Países Bajos", et: "Madalmaad", fi: "Alankomaat", fr: "Pays-Bas", ga: "An Ísiltír", hr: "Nizozemska", hu: "Hollandia", it: "Paesi Bassi", lt: "Nyderlandai", lv: "Nīderlande", mt: "Pajjiżi l-Baxxi", nl: "Nederland", pl: "Holandia", pt: "Países Baixos", ro: "Țările de Jos", sk: "Holandsko", sl: "Nizozemska", sv: "Nederländerna" },
  PL: { bg: "Полша", cs: "Polsko", da: "Polen", de: "Polen", el: "Πολωνία", en: "Poland", es: "Polonia", et: "Poola", fi: "Puola", fr: "Pologne", ga: "An Pholainn", hr: "Poljska", hu: "Lengyelország", it: "Polonia", lt: "Lenkija", lv: "Polija", mt: "Polonja", nl: "Polen", pl: "Polska", pt: "Polónia", ro: "Polonia", sk: "Poľsko", sl: "Poljska", sv: "Polen" },
  PT: { bg: "Португалия", cs: "Portugalsko", da: "Portugal", de: "Portugal", el: "Πορτογαλία", en: "Portugal", es: "Portugal", et: "Portugal", fi: "Portugali", fr: "Portugal", ga: "An Phortaingéil", hr: "Portugal", hu: "Portugália", it: "Portogallo", lt: "Portugalija", lv: "Portugāle", mt: "Portugall", nl: "Portugal", pl: "Portugalia", pt: "Portugal", ro: "Portugalia", sk: "Portugalsko", sl: "Portugalska", sv: "Portugal" },
  RO: { bg: "Румъния", cs: "Rumunsko", da: "Rumænien", de: "Rumänien", el: "Ρουμανία", en: "Romania", es: "Rumanía", et: "Rumeenia", fi: "Romania", fr: "Roumanie", ga: "An Rómáin", hr: "Rumunjska", hu: "Románia", it: "Romania", lt: "Rumunija", lv: "Rumānija", mt: "Rumanija", nl: "Roemenië", pl: "Rumunia", pt: "Roménia", ro: "România", sk: "Rumunsko", sl: "Romunija", sv: "Rumänien" },
  SK: { bg: "Словакия", cs: "Slovensko", da: "Slovakiet", de: "Slowakei", el: "Σλοβακία", en: "Slovakia", es: "Eslovaquia", et: "Slovakkia", fi: "Slovakia", fr: "Slovaquie", ga: "An tSlóvaic", hr: "Slovačka", hu: "Szlovákia", it: "Slovacchia", lt: "Slovakija", lv: "Slovākija", mt: "Slovakkja", nl: "Slowakije", pl: "Słowacja", pt: "Eslováquia", ro: "Slovacia", sk: "Slovensko", sl: "Slovaška", sv: "Slovakien" },
  SI: { bg: "Словения", cs: "Slovinsko", da: "Slovenien", de: "Slowenien", el: "Σλοβενία", en: "Slovenia", es: "Eslovenia", et: "Sloveenia", fi: "Slovenia", fr: "Slovénie", ga: "An tSlóivéin", hr: "Slovenija", hu: "Szlovénia", it: "Slovenia", lt: "Slovėnija", lv: "Slovēnija", mt: "Slovenja", nl: "Slovenië", pl: "Słowenia", pt: "Eslovénia", ro: "Slovenia", sk: "Slovinsko", sl: "Slovenija", sv: "Slovenien" },
  ES: { bg: "Испания", cs: "Španělsko", da: "Spanien", de: "Spanien", el: "Ισπανία", en: "Spain", es: "España", et: "Hispaania", fi: "Espanja", fr: "Espagne", ga: "An Spáinn", hr: "Španjolska", hu: "Spanyolország", it: "Spagna", lt: "Ispanija", lv: "Spānija", mt: "Spanja", nl: "Spanje", pl: "Hiszpania", pt: "Espanha", ro: "Spania", sk: "Španielsko", sl: "Španija", sv: "Spanien" },
  SE: { bg: "Швеция", cs: "Švédsko", da: "Sverige", de: "Schweden", el: "Σουηδία", en: "Sweden", es: "Suecia", et: "Rootsi", fi: "Ruotsi", fr: "Suède", ga: "An tSualainn", hr: "Švedska", hu: "Svédország", it: "Svezia", lt: "Švedija", lv: "Zviedrija", mt: "Iżvezja", nl: "Zweden", pl: "Szwecja", pt: "Suécia", ro: "Suedia", sk: "Švédsko", sl: "Švedska", sv: "Sverige" },
};

// Strip a leading flag emoji + spaces from a raw depNom fallback.
function stripFlag(s) {
  return String(s || "").replace(/[\u{1F1E6}-\u{1F1FF}]/gu, "").trim();
}

// Country name for an ISO code in a locale; falls back to the flag-stripped
// raw depNom (English) when the code is unknown.
function name(iso, lang, fallback) {
  const row = NAMES[iso];
  if (row && row[lang]) return row[lang];
  if (row && row.en) return row.en;
  return stripFlag(fallback) || iso || "";
}

module.exports = { name, stripFlag, NAMES };
